# Terraform pipeline

trigger:
  - master

variables:
  tf_version: "0.12.28" # what version of terraform should be used
  tf_state_rg: "AzFirewall-Handson-State-RG" # name of the resource group to create/use for the terraform state file
  tz_state_location: "japaneast" # location of the resource group to create/use for the terraform state file
  tf_state_sa_name: "terraformstate" # name of of the storage account to create/use for the terraform state file
  tf_state_container_name: "tfstate" # name of of the container to create/use for the terraform state file
  tf_state_tags: ("env=blogpost-terraform-devops-pipeline" "deployedBy=devops") # tags for the resources above which support tagging
  tf_environment: "dev" # enviroment name, used for the statefile name

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: terraformInstaller@0
    displayName: "Install Terraform $(tf_version)"
    inputs:
      terraformVersion: "$(tf_version)"

  - task: AzureCLI@2
    displayName: "Create/Check the Terraform Statefile Azure Storage Account"
    inputs:
      # azureSubscription: "$(SERVICECONNECTION_NAME)"
      connectedServiceNameARM: $(SERVICECONNECTION_NAME)
      addSpnToEnvironment: true
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        TAGS=$(tf_state_tags)
        az group create --name "$(tf_state_rg)-$(ENV_NAME)" --location $(tz_state_location) --tags "${TAGS[@]}"
        az storage account create --resource-group "$(tf_state_rg)-$(ENV_NAME)" --name "$(tf_state_sa_name)$(ENV_NAME)" --sku Standard_GRS --encryption-services blob --tags "${TAGS[@]}"
        ACCOUNT_KEY=$(az storage account keys list --resource-group "$(tf_state_rg)-$(ENV_NAME)" --account-name "$(tf_state_sa_name)$(ENV_NAME)" --query [0].value -o tsv)
        az storage container create --name $(tf_state_container_name) --account-name "$(tf_state_sa_name)$(ENV_NAME)" --account-key $ACCOUNT_KEY
        echo "##vso[task.setvariable variable=tf_state_sa_key]$ACCOUNT_KEY"

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: cp backend.tf.base backend.tf

  - task: TerraformTaskV1@0
    displayName: "Run > terraform init"
    inputs:
      command: "init"
      workingDirectory: '.'
      provider: 'azurerm'
      backendServiceArm: $(SERVICECONNECTION_NAME)
      backendAzureRmResourceGroupName: "$(tf_state_rg)-$(ENV_NAME)"
      backendAzureRmStorageAccountName: "$(tf_state_sa_name)$(ENV_NAME)"
      backendAzureRmContainerName: $(tf_state_container_name)
      backendAzureRmKey: "$(ENV_NAME).terraform.tfstate"

  - task: TerraformTaskV1@0
    displayName: "Run > terraform plan"
    inputs:
      command: "plan"
      commandOptions: -var "adminpwd=$(ADMINPWD)" -var "env=$(ENV_NAME)"
      environmentServiceNameAzureRM: $(SERVICECONNECTION_NAME)
      # 例: 会社ID が 123456 の場合
      # -var "env=123456"

  - task: TerraformTaskV1@0
    displayName: "Run > terraform apply"
    inputs:
      command: "apply"
      commandOptions: -var "adminpwd=$(ADMINPWD)" -var "env=$(ENV_NAME)"
      environmentServiceNameAzureRM: $(SERVICECONNECTION_NAME)